/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var g=Object.defineProperty;var y=Object.getOwnPropertyDescriptor;var m=Object.getOwnPropertyNames;var u=Object.prototype.hasOwnProperty;var F=(o,t)=>{for(var n in t)g(o,n,{get:t[n],enumerable:!0})},$=(o,t,n,c)=>{if(t&&typeof t=="object"||typeof t=="function")for(let a of m(t))!u.call(o,a)&&a!==n&&g(o,a,{get:()=>t[a],enumerable:!(c=y(t,a))||c.enumerable});return o};var H=o=>$(g({},"__esModule",{value:!0}),o);var w={};F(w,{default:()=>d});module.exports=H(w);var e=require("obsidian"),d=class extends e.Plugin{async onload(){this.addCommand({id:"create-health-check-note",name:"Create Health Check Note",callback:()=>this.createHealthCheckNote()}),this.addCommand({id:"create-chiari-health-check-note",name:"Create Chiari Health Check Note",callback:()=>this.createChiariHealthCheckNote()})}onunload(){}async createHealthCheckNote(){let t=new Date,n=t.getFullYear(),c=String(t.getMonth()+1).padStart(2,"0"),a=String(t.getDate()).padStart(2,"0"),p=`${n}-${c}-${a}`,h=`${p} Health Check.md`,i="Health Checks",l=`${i}/${h}`;try{this.app.vault.getAbstractFileByPath(i)||await this.app.vault.createFolder(i),await this.app.vault.create(l,`# Health Check for ${p}

- [ ] Feeling good
- [ ] Exercise completed
- [ ] Meditated
- [ ] Other notes...`);let r=this.app.vault.getAbstractFileByPath(l);r&&r instanceof e.TFile&&(this.app.workspace.getLeaf(!0).openFile(r),new e.Notice(`Health Check note created: ${h}`))}catch(s){console.error("Error creating Health Check note:",s),new e.Notice("Failed to create Health Check note.")}}async createChiariHealthCheckNote(){let t=new Date,n=t.getFullYear(),c=String(t.getMonth()+1).padStart(2,"0"),a=String(t.getDate()).padStart(2,"0"),h=`(${`${n}-${c}-${a}`})'s Chiari Check.md`,i="Chiari Checks",l=`${i}/${h}`;try{this.app.vault.getAbstractFileByPath(i)||await this.app.vault.createFolder(i);let r=`${i}/-log.md`,C=this.app.vault.getAbstractFileByPath(r);if(!C)await this.app.vault.create(r,"Log of Chiari Checks:");else{let k=await this.app.vault.cachedRead(C);await this.app.vault.modify(C,`${k}
- [[${h}]]
`)}await this.app.vault.create(l,`What level is the pain you feel (1-10)? 
- 

 Where is the pain localized? 
- 

 Have you taken any meds for the pain? 
- 


				Any additional notes... 
 - 
 - 
 -`);let f=this.app.vault.getAbstractFileByPath(l);f&&f instanceof e.TFile&&(this.app.workspace.getLeaf(!0).openFile(f),new e.Notice(`Chiari Health Check note created: ${h}`))}catch(s){console.error("Error creating Chiari Health Check note:",s),new e.Notice("Failed to create Chiari Health Check note.")}}};
